name: Build and run tests with coverage
on:
  pull_request:
    branches: [main]
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

      - name: Run linting (Ruff)
        uses: chartboost/ruff-action@e18ae971ccee1b2d7bbef113930f00c670b78da4 # v1

      - name: Install uv
        uses: astral-sh/setup-uv@180f8b44399608a850e1db031fa65c77746566d3 # v5
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Check lockfile
        run: uv lock --locked

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: |
          echo '# Code Coverage' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          uv run pytest --cov-report term --cov src >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
