name: Build and Test
on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:

env:
  AWS_REGION: ap-southeast-1
  REPOSITORY: chatbot/russell-gpt-web

permissions:
  contents: read
  id-token: write # This is required for requesting the JWT for AWS login

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

      - name: Run linting (Ruff)
        uses: chartboost/ruff-action@v1

      # Allow multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ vars.IAM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Options: https://github.com/docker/build-push-action
      - name: Build the `test` target stage of the image
        uses: docker/build-push-action@v6
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          push: false
          target: test
          platforms: linux/amd64
          # Use ECR as cache instead, as GHA has problems caching multistage images
          # https://github.com/docker/build-push-action/issues/829
          cache-to: mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${{env.REGISTRY}}/${{env.REPOSITORY}}:cache
          cache-from: type=registry,ref=${{env.REGISTRY}}/${{env.REPOSITORY}}:cache
          # https://stackoverflow.com/questions/75811044/github-action-docker-build-push-actionv4-to-ecr-returns-untagged-images
          provenance: false
